machine-type: c4-highmem-8
years:
- 2025
_total_runtime_s: 180000.0
_total_runtime_h: 50.0
_max_runtime_cap_h: 96.0
_num_benchmarks: 1
_note: Benchmarks sorted by runtime (smallest first). YAML dict order is preserved
  in Python 3.7+.
benchmarks:
  times-etimeseu-europe-elec+heat-co2-multi_stage:
    Sizes:
    - Name: 29-64ts
      Size: L
      URL: https://storage.googleapis.com/solver-benchmarks/times-etimeseu-elec%2Bheat-co2-multi_stage-29-64.mps
      _runtime_s: 180000.0
      _base_runtime_s: 36000.0
    _runtime_s: 180000.0
