NetworkExpansion: 1 # Transmission network expansion; 0 = not active; 1 = active systemwide
TimeDomainReductionFolder: "TDR_Results"
ModelingToGenerateAlternativeIterations: 3
ParameterScale: 1
EnergyShareRequirement: 0 # Minimum qualifying renewables penetration; 0 = not active; 1 = active systemwide
PrintModel: 1 # Flag for printing the model equations as .lp file. 0= the model equation won't be included as an output; 1= including the model equation as an output
TimeDomainReduction: 1 # Time domain reduce (i.e. cluster) inputs based on Demand_data.csv, Generators_variability.csv, and Fuels_data.csv; 0 = not active (use input data as provided); 0 = active (cluster input data, or use data that has already been clustered)
Trans_Loss_Segments: 1 # Number of segments used in piecewise linear approximation of transmission losses; 1 = linear, >2 = piecewise quadratic
CapacityReserveMargin: 1 # Number of capacity reserve margin constraints; 0 = not active; 1 = active systemwide
ModelingtoGenerateAlternativeSlack: 0.1
MethodofMorris: 0
StorageVirtualDischarge: 1
Reserves: 0
StorageLosses: 1 # Energy Share Requirement and CO2 constraints account for energy lost; 0 = not active (DO NOT account for energy lost); 1 = active systemwide (DO account for energy lost)
OverwriteResults: 1
UCommit: 0 # Unit committment of thermal power plants; 0 = not active; 1 = active using integer clustering; 2 = active using linearized clustering
ModelingToGenerateAlternatives: 0
MaxCapReq: 1 # Activate minimum technology carveout constraints; 0 = not active; 1 = active
MinCapReq: 1 # Activate maximum technology carveout constraints; 0 = not active; 1 = active
CO2Cap: 1 # CO2 emissions cap; 0 = not active (no CO2 emission limit); 1 = mass-based emission limit constraint; 2 = demand + rate-based emission limit constraint; 3 = generation + rate-based emission limit constraint
WriteShadowPrices: 1
