- name: pypsa-eur-sec
  sizes:
  - size: 2-24h
    url: https://storage.googleapis.com/solver-benchmarks/pypsa-eur-sec-2-24h.lp
  - size: 3-24h
    url: https://storage.googleapis.com/solver-benchmarks/pypsa-eur-sec-3-24h.lp
  - size: 4-24h
    url: https://storage.googleapis.com/solver-benchmarks/pypsa-eur-sec-4-24h.lp
  - size: 2-12h
    url: https://storage.googleapis.com/solver-benchmarks/pypsa-eur-sec-2-12h.lp
  - size: 5-24h
    url: https://storage.googleapis.com/solver-benchmarks/pypsa-eur-sec-5-24h.lp
  - size: 6-24h
    url: https://storage.googleapis.com/solver-benchmarks/pypsa-eur-sec-6-24h.lp
  - size: 7-24h
    url: https://storage.googleapis.com/solver-benchmarks/pypsa-eur-sec-7-24h.lp
  - size: 8-24h
    url: https://storage.googleapis.com/solver-benchmarks/pypsa-eur-sec-8-24h.lp
  - size: 3-12h
    url: https://storage.googleapis.com/solver-benchmarks/pypsa-eur-sec-3-12h.lp
  - size: 9-24h
    url: https://storage.googleapis.com/solver-benchmarks/pypsa-eur-sec-9-24h.lp
  - size: 10-24h
    url: https://storage.googleapis.com/solver-benchmarks/pypsa-eur-sec-10-24h.lp
  - size: 4-12h
    url: https://storage.googleapis.com/solver-benchmarks/pypsa-eur-sec-4-12h.lp
  - size: 5-12h
    url: https://storage.googleapis.com/solver-benchmarks/pypsa-eur-sec-5-12h.lp
  - size: 2-3h
    url: https://storage.googleapis.com/solver-benchmarks/pypsa-eur-sec-2-3h.lp
- name: pypsa-eur-elec-trex
  sizes:
  - size: 2-24h
    url: https://storage.googleapis.com/solver-benchmarks/pypsa-eur-elec-trex-2-24h.lp
  - size: 3-24h
    url: https://storage.googleapis.com/solver-benchmarks/pypsa-eur-elec-trex-3-24h.lp
  - size: 4-24h
    url: https://storage.googleapis.com/solver-benchmarks/pypsa-eur-elec-trex-4-24h.lp
  - size: 2-12h
    url: https://storage.googleapis.com/solver-benchmarks/pypsa-eur-elec-trex-2-12h.lp
  - size: 5-24h
    url: https://storage.googleapis.com/solver-benchmarks/pypsa-eur-elec-trex-5-24h.lp
  - size: 3-12h
    url: https://storage.googleapis.com/solver-benchmarks/pypsa-eur-elec-trex-3-12h.lp
  - size: 6-24h
    url: https://storage.googleapis.com/solver-benchmarks/pypsa-eur-elec-trex-6-24h.lp
  - size: 7-24h
    url: https://storage.googleapis.com/solver-benchmarks/pypsa-eur-elec-trex-7-24h.lp
  - size: 8-24h
    url: https://storage.googleapis.com/solver-benchmarks/pypsa-eur-elec-trex-8-24h.lp
  - size: 4-12h
    url: https://storage.googleapis.com/solver-benchmarks/pypsa-eur-elec-trex-4-12h.lp
  - size: 10-24h
    url: https://storage.googleapis.com/solver-benchmarks/pypsa-eur-elec-trex-10-24h.lp
  - size: 5-12h
    url: https://storage.googleapis.com/solver-benchmarks/pypsa-eur-elec-trex-5-12h.lp
  - size: 9-24h
    url: https://storage.googleapis.com/solver-benchmarks/pypsa-eur-elec-trex-9-24h.lp
  - size: 6-12h
    url: https://storage.googleapis.com/solver-benchmarks/pypsa-eur-elec-trex-6-12h.lp
  - size: 7-12h
    url: https://storage.googleapis.com/solver-benchmarks/pypsa-eur-elec-trex-7-12h.lp
  - size: 2-3h
    url: https://storage.googleapis.com/solver-benchmarks/pypsa-eur-elec-trex-2-3h.lp
  - size: 8-12h
    url: https://storage.googleapis.com/solver-benchmarks/pypsa-eur-elec-trex-8-12h.lp
  - size: 10-12h
    url: https://storage.googleapis.com/solver-benchmarks/pypsa-eur-elec-trex-10-12h.lp
  - size: 9-12h
    url: https://storage.googleapis.com/solver-benchmarks/pypsa-eur-elec-trex-9-12h.lp
  - size: 3-3h
    url: https://storage.googleapis.com/solver-benchmarks/pypsa-eur-elec-trex-3-3h.lp
  - size: 4-3h
    url: https://storage.googleapis.com/solver-benchmarks/pypsa-eur-elec-trex-4-3h.lp
  - size: 2-1h
    url: https://storage.googleapis.com/solver-benchmarks/pypsa-eur-elec-trex-2-1h.lp
- name: pypsa-eur-elec-op
  sizes:
  - size: 2-24h
    url: https://storage.googleapis.com/solver-benchmarks/pypsa-eur-elec-op-2-24h.lp
  - size: 3-24h
    url: https://storage.googleapis.com/solver-benchmarks/pypsa-eur-elec-op-3-24h.lp
  - size: 2-12h
    url: https://storage.googleapis.com/solver-benchmarks/pypsa-eur-elec-op-2-12h.lp
  - size: 4-24h
    url: https://storage.googleapis.com/solver-benchmarks/pypsa-eur-elec-op-4-24h.lp
  - size: 5-24h
    url: https://storage.googleapis.com/solver-benchmarks/pypsa-eur-elec-op-5-24h.lp
  - size: 3-12h
    url: https://storage.googleapis.com/solver-benchmarks/pypsa-eur-elec-op-3-12h.lp
  - size: 6-24h
    url: https://storage.googleapis.com/solver-benchmarks/pypsa-eur-elec-op-6-24h.lp
  - size: 4-12h
    url: https://storage.googleapis.com/solver-benchmarks/pypsa-eur-elec-op-4-12h.lp
  - size: 7-24h
    url: https://storage.googleapis.com/solver-benchmarks/pypsa-eur-elec-op-7-24h.lp
  - size: 8-24h
    url: https://storage.googleapis.com/solver-benchmarks/pypsa-eur-elec-op-8-24h.lp
  - size: 2-3h
    url: https://storage.googleapis.com/solver-benchmarks/pypsa-eur-elec-op-2-3h.lp
  - size: 9-24h
    url: https://storage.googleapis.com/solver-benchmarks/pypsa-eur-elec-op-9-24h.lp
  - size: 5-12h
    url: https://storage.googleapis.com/solver-benchmarks/pypsa-eur-elec-op-5-12h.lp
  - size: 10-24h
    url: https://storage.googleapis.com/solver-benchmarks/pypsa-eur-elec-op-10-24h.lp
  - size: 6-12h
    url: https://storage.googleapis.com/solver-benchmarks/pypsa-eur-elec-op-6-12h.lp
  - size: 7-12h
    url: https://storage.googleapis.com/solver-benchmarks/pypsa-eur-elec-op-7-12h.lp
  - size: 8-12h
    url: https://storage.googleapis.com/solver-benchmarks/pypsa-eur-elec-op-8-12h.lp
  - size: 9-12h
    url: https://storage.googleapis.com/solver-benchmarks/pypsa-eur-elec-op-9-12h.lp
  - size: 10-12h
    url: https://storage.googleapis.com/solver-benchmarks/pypsa-eur-elec-op-10-12h.lp
  - size: 3-3h
    url: https://storage.googleapis.com/solver-benchmarks/pypsa-eur-elec-op-3-3h.lp
  - size: 4-3h
    url: https://storage.googleapis.com/solver-benchmarks/pypsa-eur-elec-op-4-3h.lp
  - size: 2-1h
    url: https://storage.googleapis.com/solver-benchmarks/pypsa-eur-elec-op-2-1h.lp
- name: pypsa-eur-elec-op-ucconv
  sizes:
  - size: 2-24h
    url: https://storage.googleapis.com/solver-benchmarks/pypsa-eur-elec-op-ucconv-2-24h.lp
  - size: 2-12h
    url: https://storage.googleapis.com/solver-benchmarks/pypsa-eur-elec-op-ucconv-2-12h.lp
  - size: 3-24h
    url: https://storage.googleapis.com/solver-benchmarks/pypsa-eur-elec-op-ucconv-3-24h.lp
  - size: 3-12h
    url: https://storage.googleapis.com/solver-benchmarks/pypsa-eur-elec-op-ucconv-3-12h.lp
  - size: 6-24h
    url: https://storage.googleapis.com/solver-benchmarks/pypsa-eur-elec-op-ucconv-6-24h.lp
  - size: 5-24h
    url: https://storage.googleapis.com/solver-benchmarks/pypsa-eur-elec-op-ucconv-5-24h.lp
  - size: 6-12h
    url: https://storage.googleapis.com/solver-benchmarks/pypsa-eur-elec-op-ucconv-6-12h.lp
  - size: 5-12h
    url: https://storage.googleapis.com/solver-benchmarks/pypsa-eur-elec-op-ucconv-5-12h.lp
  - size: 4-12h
    url: https://storage.googleapis.com/solver-benchmarks/pypsa-eur-elec-op-ucconv-4-12h.lp
  - size: 9-24h
    url: https://storage.googleapis.com/solver-benchmarks/pypsa-eur-elec-op-ucconv-9-24h.lp
  - size: 8-24h
    url: https://storage.googleapis.com/solver-benchmarks/pypsa-eur-elec-op-ucconv-8-24h.lp
  - size: 4-24h
    url: https://storage.googleapis.com/solver-benchmarks/pypsa-eur-elec-op-ucconv-4-24h.lp
  - size: 8-12h
    url: https://storage.googleapis.com/solver-benchmarks/pypsa-eur-elec-op-ucconv-8-12h.lp
  - size: 7-12h
    url: https://storage.googleapis.com/solver-benchmarks/pypsa-eur-elec-op-ucconv-7-12h.lp
  - size: 2-3h
    url: https://storage.googleapis.com/solver-benchmarks/pypsa-eur-elec-op-ucconv-2-3h.lp
  - size: 7-24h
    url: https://storage.googleapis.com/solver-benchmarks/pypsa-eur-elec-op-ucconv-7-24h.lp
  - size: 10-24h
    url: https://storage.googleapis.com/solver-benchmarks/pypsa-eur-elec-op-ucconv-10-24h.lp
  - size: 9-12h
    url: https://storage.googleapis.com/solver-benchmarks/pypsa-eur-elec-op-ucconv-9-12h.lp
  - size: 3-3h
    url: https://storage.googleapis.com/solver-benchmarks/pypsa-eur-elec-op-ucconv-3-3h.lp
  - size: 2-1h
    url: https://storage.googleapis.com/solver-benchmarks/pypsa-eur-elec-op-ucconv-2-1h.lp
- name: pypsa-gas+wind+sol+ely
  sizes:
  - size: 1-1h
    url: https://drive.usercontent.google.com/download?id=1fEiHuIwIxbkeu-QLuOZV2yeTeH3O1zbm&export=download&authuser=0&confirm=t
- name: pypsa-gas+wind+sol+ely-ucgas
  sizes:
  - size: 1-1h
    url: https://drive.usercontent.google.com/download?id=11jEBh4ypLqRgnP5DsQ2NkZomU4FjnDRU&export=download&authuser=0&confirm=t
