benchmarks:
  - name: "pypsa-eur-sec-2-24h.lp"
    url: "TODO"
  - name: "pypsa-eur-sec-3-24h.lp"
    url: "TODO"
  - name: "pypsa-eur-sec-4-24h.lp"
    url: "TODO"
  - name: "pypsa-eur-sec-5-24h.lp"
    url: "TODO"
  - name: "pypsa-eur-sec-6-24h.lp"
    url: "TODO"
  - name: "pypsa-eur-sec-7-24h.lp"
    url: "TODO"
  - name: "pypsa-eur-sec-8-24h.lp"
    url: "TODO"
  - name: "pypsa-eur-sec-9-24h.lp"
    url: "TODO"
  - name: "pypsa-eur-sec-10-24h.lp"
    url: "TODO"
