- name: pypsa-eur-sec
  sizes:
  - size: 2-24h
    url: https://storage.googleapis.com/solver-benchmarks/pypsa-eur-sec-2-24h.lp
- name: pypsa-eur-elec-trex
  sizes:
  - size: 2-24h
    url: https://storage.googleapis.com/solver-benchmarks/pypsa-eur-elec-trex-2-24h.lp
  - size: 3-24h
    url: https://storage.googleapis.com/solver-benchmarks/pypsa-eur-elec-trex-3-24h.lp
- name: pypsa-eur-elec-op
  sizes:
  - size: 2-24h
    url: https://storage.googleapis.com/solver-benchmarks/pypsa-eur-elec-op-2-24h.lp
  - size: 3-24h
    url: https://storage.googleapis.com/solver-benchmarks/pypsa-eur-elec-op-3-24h.lp
  - size: 2-12h
    url: https://storage.googleapis.com/solver-benchmarks/pypsa-eur-elec-op-2-12h.lp
- name: pypsa-eur-elec-op-ucconv
  sizes:
  - size: 2-24h
    url: https://storage.googleapis.com/solver-benchmarks/pypsa-eur-elec-op-ucconv-2-24h.lp
