name: Generate NC Files for PyPSA Benchmarks

on:
  push:
    paths:
      - 'benchmarks/**' # Trigger on changes in the benchmarks directory
  pull_request:

jobs:
  generate_nc_files:
    runs-on: ubuntu-latest
    container: snakemake/snakemake:v8.20.4 # Use the Docker container for the entire job

    steps:
      - name: Checkout Repositories
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history for versioning

      - name: Clone PyPSA-eur Repository
        run: |
            git clone --branch master https://github.com/PyPSA/pypsa-eur.git
            cd pypsa-eur
            git checkout a69373b9

      - name: Set Up Environment
        run: |
            cd pypsa-eur

            micromamba env create -f envs/environment.yaml --yes
            micromamba run -n pypsa-eur pip install git+https://github.com/open-energy-transition/linopy.git@only-generate-problem-files --no-deps
            micromamba run -n pypsa-eur snakemake results/networks/elec_s_20_ec_lv1_3h_op.nc --cores all --printshellcmds --configfile ../benchmarks/pypsa/pypsa-eur-elec-20-lv1-3h-op.yaml ; echo -e '\a'

