machine-type: c4-standard-2
years:
- 2025
solver_configuration: highs-default scip-default
problems:
  pypsa-power+ely+battery-ucgas-1-1h:
    Problem class: MILP
    Size: M
    URL: https://storage.googleapis.com/solver-benchmarks/instances/pypsa-power%2Bely%2Bbattery-ucgas-1-1h.lp.gz
  genx-2_three_zones_w_electrolyzer-3-1h:
    Problem class: MILP
    Size: M
    URL: https://raw.githubusercontent.com/jump-dev/open-energy-modeling-benchmarks/main/instances/GenX_2_three_zones_w_electrolyzer-f211ccdcc1a2145c1f4854dcc714f50d5b8fcc524bac465a2022ffb8942ffd53.mps.gz
