machine-type: c4-standard-2
years:
- 2025
solver_configuration: highs-default scip-default
problems:
  genx-3_three_zones_w_co2_capture-no_uc-3-1h:
    Problem class: LP
    Size: M
    URL: https://storage.googleapis.com/solver-benchmarks/instances/genx-3_three_zones_w_co2_capture-no_uc-3-1h.lp.gz
  Sienna_modified_RTS_GMLC_DA_sys_NetTransport_Horizon24_Day314-73-1h:
    Problem class: MILP
    Size: M
    URL: https://raw.githubusercontent.com/jump-dev/open-energy-modeling-benchmarks/main/instances/Sienna_modified_RTS_GMLC_DA_sys_NetTransport_Horizon24_Day314-868ad371df2ae99f1427c0d6f5d6af4f1c520d51224598e1dc085b0736df5955.mps.gz
